[build]
publish = "public"
command = " git config --global url.'https://oauth2:${THEMES_ACCESS_KEY}@gitlab.com/mi/my-theme.git'.insteadOf 'https://gitlab.com/mi/my-theme.git' && hugo --gc"

[context.production.environment]
HUGO_VERSION = "v0.84.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "0.84.0"
HUGO_ENV = "deploy-preview"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
HUGO_VERSION = "0.84.0"
HUGO_ENV = "branch-deploy"
HUGO_ENABLEGITINFO = "true"