name: Hugo-CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      '.github/**'

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-github]
    steps:
      - name: preparing workspace git pull documentation  
        run: |
          pwd
          ls -lA
          cd aspose-html-docs/Aspose.HTML-Documentation && git stash && git pull && cd -
      - name: preparing workspace git pull prototype and theme 
        run: |      
          pwd
          ls -lA
          cd aspose-html-docs/lutsk-aspose-prototype 
          pwd
          ls -lA
          git stash && git pull
          cd themes/lutsk-aspose-theme 
          git stash && git pull 
          cd -
          pwd
          ls -lA
      - name: preparing workspace npm install dependencies
        run: |
          pwd
          ls -lA
          cd aspose-html-docs/Aspose.HTML-Documentation
          sudo npm install -D --save autoprefixer
          sudo npm install -D --save postcss-cli
      - name: preparing workspace sync content
        run: |
          pwd
          rsync --recursive --delete --force --progress ${{ secrets.PROJECTPATH }} content/
      - name: preparing workspace clean public folder
        run: |
          pwd
          sudo rm -rf public
          ls -lA
      - name: print secret
        run: |
           echo 'PUBLICCONTENTPATH ${{ secrets.PUBLICCONTENTPATH }}' >> secret.txt
           echo 'TRANSFERPATH ${{ secrets.TRANSFERPATH }}' >> secret.txt
           echo 'DEPLOYPATH ${{ secrets.DEPLOYPATH }}' >> secret.txt
      - name: hugo build
        run: |
          pwd
          ls -lA
          hugo version
          # hugo --minify --baseURL https://docs.aspose.com/html
          hugo -c content --debug --log --print-mem --templateMetrics --minify -v --baseURL https://docs.aspose.com/html
          rsync --recursive --delete --force -e "ssh" --progress public/ ${{ secrets.TRANSFERPATH }}
      - name: hugo deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.SSHPORT }}
          script: |
            echo ${{ secrets.PUBLICCONTENTPATH }}
            # sudo rsync --recursive --delete --force --progress ${{ secrets.PUBLICCONTENTPATH }} ${{ secrets.DEPLOYPATH }}
            # sudo nginx -s reload
