name: Hugo-CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      '.github/**'

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-github]
    steps:
      - name: preparing workspace git pull documentation prototype and theme 
        run: |
          pwd
          ls -lA
          cd aspose-html-docs/Aspose.HTML-Documentation && git stash && git pull && cd -
          pwd
          ls -lA
          cd lutsk-aspose-prototype && git stash && git pull
          pwd
          ls -lA
          cd themes/lutsk-aspose-theme && git stash && git pull && cd -
          pwd
          ls -lA
      - name: preparing workspace npm install dependencies
        run: |
          sudo npm install -D --save autoprefixer
          sudo npm install -D --save postcss-cli
          pwd
          rsync --recursive --delete --force --progress ${{ secrets.PROJECTPATH }} content/
          pwd
          rm -rf public
          ll
      - name: hugo build
        run: |
          pwd
          hugo --minify --baseURL https://docs.aspose.com/html
          rsync --recursive --delete --force -e "ssh" --progress public/ ${{ secrets.TRANSFERPATH }}
      - name: hugo deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.SSHPORT }}
          script: |
            sudo rsync --recursive --delete --force --progress ${{ secrets.PUBLICCONTENTPATH }} ${{ secrets.DEPLOYPATH }}
            sudo nginx -s reload
